name: 'EKS Deployment Verification'
author: Yash Pandya
description: An action allowing you to integrate with EKS via kubectl in a Github Action, easily...
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/codal/eks-deployment-check-hook:main'
inputs:
  aws_access_key_id:
    description: Your AWS_ACCESS_KEY_ID
    required: false
  aws_secret_access_key:
    description: Your AWS_SECRET_ACCESS_KEY
    required: false
  aws_region:
    description: The region of the cluster
    required: false
  cluster_name:
    description: The cluster name
    required: true
  eks_role_arn:
      description: EKS role arn that allow access eks cluster (Mostly happen when you create your cluster with CDK).
      required: false
  namespace:
    description: The cluster namespace
    required: true
  app_name:
    description: The app name within cluster namespace
    required: true
outputs:
  deployment-check-out:
    description: The output of the deployment-check command
